frontend/models/Schedule.php
<?php

namespace app\models;

use yii\db\ActiveRecord;

class Schedule extends ActiveRecord
{
    public static function tableName()
    {
        return 'schedule';
    }
}

frontend/models/ScheduleForm.php
<?php

namespace frontend\models;

use yii\base\Model;

class ScheduleForm extends Model
{
    public $subject;
    public $content;
    public $address;
    public $from;
    public $to;
    public $owner_id;
    public $color;


    public function rules()
    {
        return [
            [['subject', 'content', 'address', 'from', 'to', 'color'], 'required'],
        ];
    }
}

frontend/controllers/ScheduleController.php
<?php

/**
 * Created by PhpStorm.
 * User: dalv
 * Date: 11/13/2015
 * Time: 12:17 PM
 */
namespace frontend\controllers;

use app\models\Schedule;
use frontend\models\FriendQuery;
use frontend\models\ScheduleForm;
use frontend\models\ScheduleQuery;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii2fullcalendar\models\Event;

class ScheduleController extends Controller
{
    public function actionIndex()
    {
        $model = new ScheduleForm();
        $schedule_query = ScheduleQuery::getInstance();
        if ($model->load(\Yii::$app->request->post())) {
            $model->owner_id = \Yii::$app->user->getId();
            $schedule_query->newSchedule($model);
        }
        $schedules = $schedule_query->getSchedules(\Yii::$app->user->getId());
        $events = $this->convert_to_events($schedules);
        return $this->render('index', ['model' => $model, 'events' => $events, 'friends' => $friends]);
    }

    public function actionEdit($id)
    {
        $model = new ScheduleForm();

        $schedule = Schedule::findOne(['id' => $id]);
        $this->init_schedule_form($model, $schedule);

        $schedule_query = ScheduleQuery::getInstance();
        $schedules = $schedule_query->getSchedules(\Yii::$app->user->getId());

        $events = $this->convert_to_events($schedules);
        if ($model->load(\Yii::$app->request->post())) {
            $model->owner_id = \Yii::$app->user->getId();
            $schedules = $schedule_query->getSchedules(\Yii::$app->user->getId());
            $events = $this->convert_to_events($schedules);
            $schedule_query->editSchedule($model, $id);
            return $this->render('index', ['model' => $model, 'events' => $events, 'edit' => true, 'edited' => true]);
        }
        return $this->render('index', ['model' => $model, 'events' => $events, 'edit' => true]);
    }

    public function actionDetail($id)
    {
        $schedule_query = ScheduleQuery::getInstance();
        $schedule = $schedule_query->getSchedule($id);
        if (empty($schedule)) {
            return new BadRequestHttpException();
        }
        return $this->render('detail', ['schedule' => $schedule]);
    }

    public function actionDelete()
    {
        if (isset($_POST['id'])) {
            $schedule_id = $_POST['id'];
            $schedule_query = ScheduleQuery::getInstance();
            if ($schedule_query->delete($schedule_id)) {
                return "YES";
            } else {
                return "NO";
            }
        }
    }

    private function convert_to_events($schedules)
    {

        $events[] = array();
        $index = 0;
        foreach ($schedules as $schedule) {
            $event = new Event();
            $event->id = $schedule['id'];
            $event->title = $schedule['subject'];
            $event->start = date('Y-m-d\TH:i:s\Z', strtotime($schedule['from']));
            $event->end = date('Y-m-d\TH:i:s\Z', strtotime($schedule['to']));
            $event->url = '?r=schedule/detail&id=' . $schedule['id'];
            $event->backgroundColor = $schedule['color'];
            $events[$index++] = $event;
        }
        return $events;
    }

    private function init_schedule_form($model, $schedule)
    {
        $model['subject'] = $schedule['subject'];
        $model['content'] = $schedule['content'];
        $model['address'] = $schedule['address'];
        $model['from'] = $schedule['from'];
        $model['to'] = $schedule['to'];
        $model['color'] = $schedule['color'];
    }

    private function toSelectData($friends)
    {
        $data = [];
        foreach ($friends as $friend) {
            $data[$friend['id']] = $friend['full_name'];
        }
        return $data;
    }

    private function toMapString($assigned_users)
    {
        $results = [];
        foreach ($assigned_users as $user) {
            $results[$user['id']] = $user['full_name'];
        }
        return $results;
    }
}

frontend/views/schedule/detail.php
<?php

use yii\helpers\Html;

$this->title = 'Chi tiết lịch';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-lg-12">
        <div class="box box-primary" style="border-color: <?= $schedule['color'] ?>">
            <div class="box-header with-border">
                <h3 class="box-title">Lịch của bạn</h3>

                <div class="box-tools">
                    <a href="<?= \yii\helpers\Url::to(['schedule/edit', 'id' => $schedule['id']]) ?>"
                       class="btn btn-box-tool" title="Chỉnh sửa"><i class="fa fa-edit"></i></a>
                    <a class="btn btn-box-tool delete-schedule" id="<?= $schedule['id'] ?>"
                       title="Xóa"><i class="fa fa-trash"></i></a>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <?php
                if ($schedule['owner_id'] != Yii::$app->user->getId()) {
                ?>
                <strong><i class="fa fa-user"></i> Người gửi</strong>
            <br>
                <a href="<?= \yii\helpers\Url::to(['user/profile', 'id' => $schedule['owner_id']]) ?>">
                    <?php
                    if (!empty($schedule['image'])) {
                        echo Html::img(Yii::$app->request->baseUrl . '/images/' . $schedule['image'],
                            [
                                'title' => $schedule['full_name'],
                                'class' => 'img-circle',
                                'style' => 'width:40px;height:40px;border-radius: 50%;border: 2px solid #dd4b39;',
                            ]
                        );

                    } else {
                        echo Html::img(Yii::$app->request->baseUrl . '/images/default.jpg',
                            [
                                'title' => $schedule['full_name'],
                                'class' => 'img-circle',
                                'style' => 'width:40px;height:40px;border-radius: 50%;border: 2px solid #dd4b39;',
                            ]
                        );
                    }
                    }
                    ?>
                </a>

                <strong><i class="fa fa-object-group"></i> Chủ đề</strong>

                <p class="text-muted">
                    <?= $schedule['subject'] ?>
                </p>

                <hr>

                <strong><i class="fa fa-file-text-o margin-r-5"></i> Nội dung</strong>

                <p class="text-muted"><?= $schedule['content'] ?></p>

                <hr>

                <strong><i class="fa fa-anchor"></i> Địa điểm</strong>

                <p><?= $schedule['address'] ?></p>

                <hr>

                <strong><i class="fa fa-calendar"></i> Thời gian</strong>

                <p>Từ: <?= $schedule['from'] ?></p>

                <p>Đến: <?= $schedule['to'] ?></p>

                <div class="box-footer clearfix">
                    <a href="?r=schedule/index" class="pull-left btn btn-default"><i
                            class="fa fa-arrow-circle-left"></i> Quay trở lại</a>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
    </div>
</div>

frontend/views/schedule/index.php
<?php

use kartik\color\ColorInput;
use kartik\datetime\DateTimePicker;
use kartik\select2\Select2;
use yii\helpers\Html;

$this->title = 'Lịch làm việc';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php
if (isset($edited)) {
    ?>
    <div class="callout callout-success">
        <h4>Chỉnh sửa lịch làm việc thành công!</h4>

        <p>Bạn đã chỉnh sửa lịch làm việc thành công.</p>
    </div>
    <?php
}
?>
<div class="row">
    <div class="col-lg-3">
        <div class="box box-solid">
            <div class="box-header with-border">
                <?php
                if (isset($edit)) {
                    ?>
                    <h3 class="box-title">Chỉnh sửa lịch làm việc</h3>
                    <?php
                } else {
                    ?>
                    <h3 class="box-title">Tạo mới lịch làm việc</h3>
                    <?php
                }
                ?>
            </div>
            <?php
            $form = \yii\widgets\ActiveForm::begin();
            ?>
            <div class="input" style="padding: 10px 10px 10px 10px;">
                <?= $form->field($model, 'subject')->textInput(['placeholder' => 'Enter subject']) ?>

                <?= $form->field($model, 'content')->textarea(['placeholder' => 'Enter content']) ?>

                <?= $form->field($model, 'address')->textInput(['placeholder' => 'Enter address']) ?>

                <?= $form->field($model, 'from')->widget(DateTimePicker::className(), [
                    'options' => ['placeholder' => 'From'],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd  hh:ii:ss'
                    ],
                ]) ?>

                <?= $form->field($model, 'to')->widget(DateTimePicker::className(), [
                    'options' => ['placeholder' => 'To'],
                    'pluginOptions' => [
                        'format' => 'yyyy-mm-dd hh:ii:ss'
                    ],
                ]) ?>

                <?= $form->field($model, 'color')->widget(ColorInput::className(), [
                    'value' => '#00ff00',
                    'options' => ['placeholder' => 'Color'],
                    'attribute' => 'saturation',
                ]) ?>

                <br>
                <?= Html::submitButton('New', ['class' => 'btn btn-success', 'name' => 'new-schedule']) ?>
            </div>
            <?php
            \yii\widgets\ActiveForm::end();
            ?>
        </div>
    </div>
    <div class="col-lg-9">
        <?php
        /** @var Array[] $events */
        echo \yii2fullcalendar\yii2fullcalendar::widget(array(
            'events' => $events,
        ));
        ?>
    </div>
</div>